// Bancos do Brasil — instituições com código COMPE (fonte: BrasilAPI /banks/v1).
// Lista estática que popula o autocomplete do campo "Banco / Instituição".
// Marcas populares têm nome curado; as demais usam o nome COMPE oficial normalizado.
// Gerado automaticamente — não editar à mão (regerar a partir da BrasilAPI).

export interface BrBank {
  /** Código COMPE com 3 dígitos (ex.: "237"). */
  code: string
  /** Nome de exibição (marca curada ou nome COMPE normalizado). */
  name: string
}

/** Rótulo "código - nome" exibido no datalist (ex.: "237 - Bradesco"). */
export function brBankLabel(b: BrBank): string {
  return `${b.code} - ${b.name}`
}

export const BR_BANKS: BrBank[] = [
  { code: "001", name: "Banco do Brasil" },
  { code: "003", name: "Banco da Amazônia" },
  { code: "004", name: "Banco do Nordeste" },
  { code: "007", name: "Bndes" },
  { code: "010", name: "Credicoamo" },
  { code: "011", name: "UBS (Brasil) Corretora de Valores S.A." },
  { code: "012", name: "Banco Inbursa" },
  { code: "014", name: "State Street BR S.A. Banco Comercial" },
  { code: "015", name: "UBS BB CCTVM S.A." },
  { code: "016", name: "CCM Desp Trâns SC e RS" },
  { code: "017", name: "BNY Mellon Banco S.A." },
  { code: "018", name: "Banco Tricury S.A." },
  { code: "021", name: "Banestes" },
  { code: "024", name: "Banco Bandepe S.A." },
  { code: "025", name: "Banco Alfa" },
  { code: "033", name: "Santander" },
  { code: "036", name: "Banco Bbi S.A." },
  { code: "037", name: "Banco do Est. do Pa S.A." },
  { code: "040", name: "Banco Cargill S.A." },
  { code: "041", name: "Banrisul" },
  { code: "047", name: "Banco do Est. de Se S.A." },
  { code: "060", name: "Confidence CC S.A." },
  { code: "063", name: "Banco Bradescard" },
  { code: "064", name: "Goldman Sachs do Brasil BM S.A" },
  { code: "065", name: "Banco Andbank S.A." },
  { code: "066", name: "Banco Morgan Stanley S.A." },
  { code: "069", name: "Banco Crefisa" },
  { code: "070", name: "BRB - Banco de Brasília" },
  { code: "074", name: "Banco J. Safra" },
  { code: "075", name: "Banco Abn Amro Clearing S.A." },
  { code: "076", name: "Banco KDB Brasil S.A." },
  { code: "077", name: "Banco Inter" },
  { code: "078", name: "Haitong Bi do Brasil S.A." },
  { code: "079", name: "Picpay Bank - Banco Múltiplo S.A" },
  { code: "080", name: "BT CC Ltda." },
  { code: "081", name: "Bancoseguro S.A." },
  { code: "082", name: "Banco Topázio S.A." },
  { code: "083", name: "Banco da China Brasil S.A." },
  { code: "084", name: "Sisprime do Brasil - Coop" },
  { code: "085", name: "Ailos" },
  { code: "088", name: "Banco Randon S.A." },
  { code: "089", name: "Credisan CC" },
  { code: "093", name: "Polocred SCMEPP Ltda." },
  { code: "094", name: "Banco Finaxis" },
  { code: "095", name: "Banco Travelex S.A." },
  { code: "096", name: "Banco B3 S.A." },
  { code: "097", name: "Credisis - Central de Cooperativas de Crédito Ltda." },
  { code: "099", name: "Uniprime Coopcentral Ltda." },
  { code: "100", name: "Planner CV S.A." },
  { code: "101", name: "Warren Rena DTVM" },
  { code: "102", name: "XP Investimentos" },
  { code: "104", name: "Caixa Econômica Federal" },
  { code: "105", name: "Lecca CFI S.A." },
  { code: "107", name: "Banco Bocom BBM S.A." },
  { code: "111", name: "Oliveira Trust DTVM S.A." },
  { code: "113", name: "Neon CTVM S.A." },
  { code: "119", name: "Banco Western Union" },
  { code: "120", name: "Banco Rodobens S.A." },
  { code: "121", name: "Agibank" },
  { code: "122", name: "Banco Bradesco Berj S.A." },
  { code: "124", name: "Banco Woori Bank do Brasil S.A." },
  { code: "125", name: "Banco Genial" },
  { code: "126", name: "BR Partners Bi" },
  { code: "127", name: "Codepe CVC S.A." },
  { code: "128", name: "Braza Bank S.A. Banco de Câmbio" },
  { code: "129", name: "UBS BB Bi S.A." },
  { code: "130", name: "Caruana SCFI" },
  { code: "131", name: "Tullett Prebon Brasil CVC Ltda" },
  { code: "132", name: "Icbc do Brasil BM S.A." },
  { code: "133", name: "Cresol Confederação" },
  { code: "134", name: "BGC Liquidez DTVM Ltda" },
  { code: "136", name: "Unicred" },
  { code: "138", name: "Get Money CC Ltda" },
  { code: "139", name: "Intesa Sanpaolo Brasil S.A. BM" },
  { code: "140", name: "Nu Investimentos S.A. - CTVM" },
  { code: "141", name: "Master Bi S.A. - Em Liquidação Extrajudicial" },
  { code: "142", name: "Broker Brasil CC Ltda." },
  { code: "143", name: "Intex Bank Banco de Câmbio S.A." },
  { code: "144", name: "Ebury Banco de Câmbio S.A." },
  { code: "145", name: "Levycam CCV Ltda" },
  { code: "146", name: "Guitta CC Ltda" },
  { code: "149", name: "Facta S.A. CFI" },
  { code: "157", name: "Icap do Brasil CTVM Ltda." },
  { code: "159", name: "Casa Credito S.A. SCM" },
  { code: "173", name: "BRL Trust DTVM SA" },
  { code: "174", name: "Pefisa S.A. - C.F.I." },
  { code: "180", name: "CM Capital Markets CCTVM Ltda" },
  { code: "183", name: "Socred SA - SCMEPP" },
  { code: "188", name: "Ativa S.A. Investimentos CCTVM" },
  { code: "189", name: "HS Financeira" },
  { code: "190", name: "Servicoop" },
  { code: "191", name: "Nova Futura CTVM Ltda." },
  { code: "194", name: "Unida DTVM Ltda" },
  { code: "195", name: "Valor S/A SCFI" },
  { code: "196", name: "Fair Sociedade CC" },
  { code: "197", name: "Stone" },
  { code: "208", name: "BTG Pactual" },
  { code: "212", name: "Banco Original" },
  { code: "213", name: "Banco Arbi S.A." },
  { code: "217", name: "Banco John Deere S.A." },
  { code: "218", name: "Banco BS2" },
  { code: "222", name: "Banco Crédit Agricole BR S.A." },
  { code: "224", name: "Banco Fibra S.A." },
  { code: "233", name: "Banco BMG Soluções Financeiras S.A." },
  { code: "237", name: "Bradesco" },
  { code: "241", name: "Banco Classico S.A." },
  { code: "243", name: "Banco Master - Em Liquidação Extrajudicial" },
  { code: "246", name: "Banco ABC Brasil" },
  { code: "249", name: "Banco Investcred Unibanco S.A." },
  { code: "250", name: "Banco BMG Consignado S.A." },
  { code: "254", name: "Parana Banco S.A." },
  { code: "259", name: "Moneycorp Banco de Câmbio S.A." },
  { code: "260", name: "Nubank" },
  { code: "265", name: "Banco Fator S.A." },
  { code: "266", name: "Banco Cedula S.A." },
  { code: "268", name: "Bari Cia Hipotecária" },
  { code: "269", name: "Banco HSBC S.A." },
  { code: "271", name: "BPY CCTVM S.A." },
  { code: "272", name: "Agk CC S.A." },
  { code: "273", name: "Coop Sulcredi Amplea" },
  { code: "274", name: "BMP SCMEPP Ltda" },
  { code: "276", name: "Banco Senff S.A." },
  { code: "278", name: "Genial Investimentos CVM S.A." },
  { code: "280", name: "Will Financeira S.A.Cfi - Em Liquidação Extrajudicial" },
  { code: "281", name: "CCR Coopavel" },
  { code: "283", name: "RB Investimentos DTVM Ltda." },
  { code: "285", name: "Frente SCC S.A - Em Liquidação Extrajudicial" },
  { code: "288", name: "Carol DTVM Ltda." },
  { code: "289", name: "Efx CC Ltda." },
  { code: "290", name: "PagBank (PagSeguro)" },
  { code: "292", name: "Galapagos DTVM S.A." },
  { code: "293", name: "Lastro RDV DTVM Ltda" },
  { code: "296", name: "Oz Corretora de Câmbio S.A." },
  { code: "298", name: "Vips CC S.A." },
  { code: "299", name: "Banco Afinz S.A. - BM" },
  { code: "300", name: "Banco La Nacion Argentina" },
  { code: "301", name: "Dock IP S.A." },
  { code: "305", name: "Fourtrade Cor. de Cambio Ltda" },
  { code: "307", name: "Terra Investimentos DTVM" },
  { code: "310", name: "Vortx DTVM Ltda." },
  { code: "312", name: "HSCM SCMEPP Ltda." },
  { code: "318", name: "Banco BMG" },
  { code: "319", name: "Om DTVM Ltda" },
  { code: "320", name: "Boc Brasil" },
  { code: "321", name: "Crefaz SCMEPP SA" },
  { code: "322", name: "CCR de Abelardo Luz" },
  { code: "323", name: "Mercado Pago" },
  { code: "324", name: "Cartos SCD S.A." },
  { code: "326", name: "Parati - CFI S.A." },
  { code: "328", name: "Cecm Fabric Calçados Sapiranga" },
  { code: "329", name: "Qi SCD S.A." },
  { code: "330", name: "Banco Bari S.A." },
  { code: "331", name: "Oslo Capital DTVM SA" },
  { code: "332", name: "Acesso Soluções de Pagamento S.A. - Instituição de Pagamento" },
  { code: "334", name: "Banco Besa S.A." },
  { code: "335", name: "Banco Digio" },
  { code: "336", name: "C6 Bank" },
  { code: "341", name: "Itaú Unibanco" },
  { code: "342", name: "Creditas SCD" },
  { code: "348", name: "Banco XP" },
  { code: "349", name: "Al5 S.A. SCFI" },
  { code: "350", name: "Coop de Agricultores e Aeroportuários do Brasil" },
  { code: "352", name: "Santander CTVM S.A." },
  { code: "355", name: "Ótimo SCD S.A." },
  { code: "358", name: "Midway S.A. - SCFI" },
  { code: "359", name: "Zema CFI S/A" },
  { code: "360", name: "Trinus Capital DTVM" },
  { code: "362", name: "Cielo IP S.A." },
  { code: "363", name: "Qi CTVM S.A." },
  { code: "364", name: "Efí S.A. - IP" },
  { code: "365", name: "Simpaul" },
  { code: "366", name: "Banco Societe Generale Brasil" },
  { code: "368", name: "Banco CSF S.A." },
  { code: "370", name: "Banco Mizuho S.A." },
  { code: "373", name: "Up.P Sep S.A." },
  { code: "374", name: "Realize SCFI S.A." },
  { code: "376", name: "Banco J.P. Morgan S.A." },
  { code: "377", name: "BMS SCD S.A." },
  { code: "378", name: "Banco Brasileiro de Crédito S.A." },
  { code: "379", name: "Coop Cooperforte Ltda." },
  { code: "380", name: "PicPay" },
  { code: "381", name: "Banco Mercedes-Benz S.A." },
  { code: "382", name: "Fiducia SCMEPP Ltda" },
  { code: "383", name: "Ebanx IP Ltda." },
  { code: "384", name: "Global SCM Ltda" },
  { code: "385", name: "Cecm dos Trab.Port. da G.Vitor" },
  { code: "386", name: "Nu Financeira S.A. CFI" },
  { code: "387", name: "Banco Toyota do Brasil S.A." },
  { code: "389", name: "Banco Mercantil do Brasil S.A." },
  { code: "390", name: "Banco GM S.A." },
  { code: "391", name: "CCR de Ibiam" },
  { code: "393", name: "Banco Volkswagen S.A" },
  { code: "394", name: "Bradesco Financiamentos" },
  { code: "395", name: "F D Gold DTVM Ltda" },
  { code: "396", name: "Magalupay" },
  { code: "397", name: "Listo SCD S.A." },
  { code: "398", name: "Ideal CTVM S.A." },
  { code: "399", name: "Kirton Bank" },
  { code: "400", name: "Coop Creditag - Em Liquidação Extrajudicial" },
  { code: "401", name: "Iugu IP S.A." },
  { code: "402", name: "Cobuccio S.A. SCFI" },
  { code: "403", name: "Cora SCFI" },
  { code: "404", name: "Sumup SCD S.A." },
  { code: "406", name: "Accredito SCD S.A." },
  { code: "407", name: "Sefer Investimentos DTVM Ltda" },
  { code: "408", name: "Bonuspago SCD S.A." },
  { code: "410", name: "Planner Sociedade de Crédito Direto" },
  { code: "411", name: "Via Certa Financiadora S.A. - CFI" },
  { code: "412", name: "Social Bank S/A" },
  { code: "413", name: "Banco BV S.A." },
  { code: "414", name: "Lend SCD S.A." },
  { code: "415", name: "Banco Nacional" },
  { code: "416", name: "Lamara SCD S.A." },
  { code: "418", name: "Zipdin SCD S.A." },
  { code: "419", name: "Numbrs SCD S.A." },
  { code: "421", name: "CC Lar Credi" },
  { code: "422", name: "Banco Safra" },
  { code: "423", name: "Coluna S.A. DTVM" },
  { code: "425", name: "Socinal S.A. CFI" },
  { code: "426", name: "Neon Financeira - SCFI S.A." },
  { code: "427", name: "Cred.Ufes" },
  { code: "428", name: "Credsystem SCD S.A." },
  { code: "430", name: "CCR Seara" },
  { code: "433", name: "Br-Capital DTVM S.A." },
  { code: "435", name: "Delfinance SCD S.A." },
  { code: "438", name: "Trustee DTVM Ltda." },
  { code: "439", name: "Id CTVM" },
  { code: "440", name: "Coop Credi&gente" },
  { code: "443", name: "Octa SCD S.A. - Em Liquidação Extrajudicial" },
  { code: "444", name: "Trinus SCD S.A." },
  { code: "445", name: "Plantae CFI" },
  { code: "447", name: "Mirae Asset (Brasil) CCTVM Ltda." },
  { code: "448", name: "Hemera DTVM Ltda." },
  { code: "449", name: "DM" },
  { code: "450", name: "Fits IP" },
  { code: "451", name: "J17 - SCD S/A" },
  { code: "452", name: "Credifit SCD S.A." },
  { code: "454", name: "Mérito DTVM Ltda." },
  { code: "455", name: "Vis DTVM Ltda" },
  { code: "456", name: "Banco MUFG Brasil S.A." },
  { code: "457", name: "Uy3 SCD S/A" },
  { code: "458", name: "Hedge Investments DTVM Ltda." },
  { code: "460", name: "Unavanti SCD S/A" },
  { code: "461", name: "Asaas IP S.A." },
  { code: "462", name: "Stark SCD S.A." },
  { code: "463", name: "Azumi DTVM" },
  { code: "464", name: "Banco Sumitomo Mitsui Brasil S.A." },
  { code: "465", name: "Capital Consig SCD S.A." },
  { code: "467", name: "Master S/A CCTVM - Em Liquidação Extrajudicial" },
  { code: "468", name: "Portoseg S.A. CFI" },
  { code: "469", name: "Picpay Invest" },
  { code: "470", name: "CDC SCD S.A." },
  { code: "473", name: "Banco Caixa Geral Brasil S.A." },
  { code: "475", name: "Banco Yamaha Motor S.A." },
  { code: "476", name: "Idea Maker IP Ltda" },
  { code: "477", name: "Citibank N.A." },
  { code: "478", name: "Gazincred S.A. SCFI" },
  { code: "479", name: "Banco ItauBank" },
  { code: "481", name: "Superlógica SCD S.A." },
  { code: "482", name: "Artta SCD" },
  { code: "484", name: "Maf DTVM SA" },
  { code: "487", name: "Deutsche Bank S.A.Bco Alemao" },
  { code: "488", name: "Jpmorgan Chase Bank" },
  { code: "495", name: "Banco La Provincia B Aires Bce" },
  { code: "496", name: "Bbva Brasil Bi S.A." },
  { code: "505", name: "Banco UBS Brasil" },
  { code: "506", name: "Rji" },
  { code: "507", name: "SCFI Efí S.A." },
  { code: "508", name: "Avenue Securities Bi S.A." },
  { code: "509", name: "Celcoin IP S.A." },
  { code: "510", name: "Ffcred SCD S.A." },
  { code: "511", name: "Magnum SCD" },
  { code: "512", name: "Finvest DTVM" },
  { code: "513", name: "Atf SCD S.A." },
  { code: "514", name: "Exim CC Ltda." },
  { code: "516", name: "Qista S.A. CFI" },
  { code: "517", name: "Pagueveloz IP Ltda." },
  { code: "518", name: "Mercado Crédito SCFI S.A." },
  { code: "519", name: "Lions Trust DTVM" },
  { code: "520", name: "Somapay SCD S.A." },
  { code: "521", name: "Peak Sep S.A." },
  { code: "522", name: "Red SCD S.A." },
  { code: "523", name: "HR Digital SCD" },
  { code: "524", name: "WNT Capital DTVM" },
  { code: "525", name: "Intercam CC Ltda" },
  { code: "526", name: "Monetarie SCD" },
  { code: "527", name: "Aticca SCD S.A." },
  { code: "528", name: "CBSF DTVM -Em Liquidação Extrajudicial" },
  { code: "529", name: "Pinbank IP" },
  { code: "530", name: "Ser Finance SCD S.A." },
  { code: "531", name: "BMP SCD S.A." },
  { code: "532", name: "Futuro SCD" },
  { code: "533", name: "SRM Bank" },
  { code: "534", name: "Ewally IP S.A." },
  { code: "535", name: "Opea SCD" },
  { code: "536", name: "Neon Pagamentos S.A. IP" },
  { code: "537", name: "Microcash SCMEPP Ltda." },
  { code: "538", name: "Sudacred SCD S.A." },
  { code: "539", name: "Santinvest S.A. - CFI" },
  { code: "540", name: "Hbi SCD" },
  { code: "541", name: "Fdo Garantidor Créditos" },
  { code: "542", name: "Cloudwalk IP Ltda" },
  { code: "543", name: "Coopcrece" },
  { code: "544", name: "Multicred SCD S.A." },
  { code: "545", name: "Senso CCVM S.A." },
  { code: "546", name: "Okto IP" },
  { code: "547", name: "BNK Digital SCD S.A." },
  { code: "548", name: "RPW S.A. SCFI" },
  { code: "550", name: "Beeteller IP Ltda." },
  { code: "551", name: "Vert DTVM Ltda." },
  { code: "552", name: "Uzzipay IP S.A." },
  { code: "553", name: "Percapital SCD S.A." },
  { code: "554", name: "Banco Stonex S.A." },
  { code: "555", name: "Pan Finan" },
  { code: "556", name: "Saygo Câmbio" },
  { code: "557", name: "Pagprime IP" },
  { code: "559", name: "Kanastra CFI" },
  { code: "560", name: "Mag IP Ltda." },
  { code: "561", name: "Pay4fun IP S.A." },
  { code: "562", name: "Azimut Brasil DTVM Ltda" },
  { code: "563", name: "Protege Cash" },
  { code: "564", name: "J17 CFI S.A." },
  { code: "565", name: "Ágora CTVM S.A." },
  { code: "566", name: "Flagship IP Ltda" },
  { code: "567", name: "Mercantil Financeira" },
  { code: "568", name: "Brcondos SCD S.A." },
  { code: "569", name: "Conta Pronta IP" },
  { code: "572", name: "All In Cred SCD S.A." },
  { code: "573", name: "Oxy CH" },
  { code: "574", name: "A55 SCD S.A." },
  { code: "575", name: "DGBK Credit S.A. - Sociedade de Crédito Direto." },
  { code: "576", name: "Mercado Bitcoin IP Ltda" },
  { code: "577", name: "Af Desenvolve SP S.A." },
  { code: "579", name: "Quadra SCD" },
  { code: "580", name: "Cccpoupinv Sul e Sudeste - Central Sul/Sudeste" },
  { code: "581", name: "Central Nordeste" },
  { code: "582", name: "CCC Poup Inv de Ms, Go, DF e To" },
  { code: "583", name: "CCC Poup Inv do Centro Norte do Brasil" },
  { code: "584", name: "CCC Poup e Inv dos Estados do Pr, SP e RJ" },
  { code: "585", name: "Sethi SCD SA" },
  { code: "586", name: "Z1 IP Ltda." },
  { code: "587", name: "Fidd DTVM Ltda." },
  { code: "588", name: "Avancard Prover IP Ltda" },
  { code: "589", name: "G5 SCD SA" },
  { code: "590", name: "Repasses Financeiros e Solucoes Tecnologicas IP S.A." },
  { code: "591", name: "Banvox DTVM" },
  { code: "592", name: "Maps IP Ltda." },
  { code: "593", name: "Transfeera IP S.A." },
  { code: "594", name: "Asa SCFI S.A." },
  { code: "595", name: "Ifood Pago IP" },
  { code: "596", name: "Cactvs IP S.A." },
  { code: "597", name: "Issuer IP Ltda." },
  { code: "598", name: "Konect SCD S/A" },
  { code: "599", name: "Agoracred S/A SCFI" },
  { code: "600", name: "Banco Luso Brasileiro S.A." },
  { code: "604", name: "Banco Industrial do Brasil S.A." },
  { code: "610", name: "Banco VR S.A." },
  { code: "611", name: "Banco Paulista S.A." },
  { code: "612", name: "Banco Guanabara S.A." },
  { code: "613", name: "Omni Banco S.A." },
  { code: "614", name: "Sants SCD S.A." },
  { code: "615", name: "Smart Solutions Group IP Ltda" },
  { code: "619", name: "Trio IP Ltda." },
  { code: "620", name: "Revolut SCD S.A." },
  { code: "623", name: "Banco PAN" },
  { code: "626", name: "Banco C6 Consig" },
  { code: "630", name: "Banco Letsbank S.A. - Em Liquidação Extrajudicial" },
  { code: "632", name: "Z-On SCD S.A." },
  { code: "633", name: "Banco Rendimento S.A." },
  { code: "634", name: "Banco Triangulo S.A." },
  { code: "636", name: "Giro - SCD S/A" },
  { code: "637", name: "Banco Sofisa S.A." },
  { code: "643", name: "Banco Pine" },
  { code: "644", name: "321 SCD S.A." },
  { code: "646", name: "DM SCFI" },
  { code: "651", name: "Pagare IP S.A." },
  { code: "653", name: "BM Pleno S.A. - Em Liquidação Extrajudicial" },
  { code: "654", name: "Banco Digimais" },
  { code: "655", name: "Banco Votorantim" },
  { code: "659", name: "Onekey Payments IP S.A." },
  { code: "660", name: "Pagme IP Ltda" },
  { code: "661", name: "Freex SCC S.A." },
  { code: "662", name: "We Pay Out IP Ltda." },
  { code: "663", name: "Actual DTVM S.A." },
  { code: "664", name: "Eagle IP Ltda." },
  { code: "665", name: "Stark Bank S.A. - IP" },
  { code: "667", name: "Liquido IP Ltda" },
  { code: "668", name: "Celcoin SCD" },
  { code: "669", name: "Transfero IP Ltda." },
  { code: "670", name: "BSN" },
  { code: "671", name: "Zero IP" },
  { code: "672", name: "Stone CFI S.A." },
  { code: "673", name: "CCR do Agreste Alagoano" },
  { code: "674", name: "Hinova Pay IP S.A." },
  { code: "675", name: "Casas Bahia Pay IP Ltda." },
  { code: "676", name: "Dufrio CFI S.A." },
  { code: "678", name: "Fidem SCD S/A" },
  { code: "679", name: "Pay IP S.A." },
  { code: "680", name: "Delta Global SCD S.A." },
  { code: "681", name: "MT IP S.A." },
  { code: "682", name: "Monery IP S.A." },
  { code: "683", name: "Brasil Cash IP S.A." },
  { code: "684", name: "Harmos S.A. - SCFI" },
  { code: "685", name: "Tycoon Technology Iip S.A" },
  { code: "686", name: "Biz IP Ltda." },
  { code: "687", name: "Inco Sep S.A." },
  { code: "688", name: "Kikai SCD S.A." },
  { code: "689", name: "Nvio Brasil SCD S.A." },
  { code: "690", name: "BK IP S.A." },
  { code: "691", name: "Wasu IP Ltda." },
  { code: "692", name: "Squid SCD S.A." },
  { code: "693", name: "Efex IP" },
  { code: "694", name: "Woovi IP Ltda." },
  { code: "695", name: "Bees IP Ltda." },
  { code: "696", name: "Loan Brasil SCD S.A." },
  { code: "697", name: "JM Corretora de Câmbio" },
  { code: "698", name: "Bit SCD S.A." },
  { code: "699", name: "BFC SCD S.A." },
  { code: "700", name: "MW IP Ltda." },
  { code: "701", name: "Integração de Crédito e Cobrança SCD" },
  { code: "703", name: "Getnet IP" },
  { code: "704", name: "Festor IP Ltda." },
  { code: "707", name: "Banco Daycoval" },
  { code: "708", name: "Banco Induscred de Investim. S/A" },
  { code: "712", name: "Ouribank S.A." },
  { code: "714", name: "Finamax S.A. CFI" },
  { code: "719", name: "Banco Master Múltiplo - Em Liquidação Extrajudicial" },
  { code: "720", name: "Banco RNX S.A." },
  { code: "741", name: "Banco Ribeirao Preto S.A." },
  { code: "743", name: "Banco Semear" },
  { code: "745", name: "Citibank" },
  { code: "747", name: "Banco Rabobank Intl Brasil S.A." },
  { code: "748", name: "Sicredi" },
  { code: "751", name: "Scotiabank Brasil" },
  { code: "752", name: "Banco BNP Paribas Brasil S A" },
  { code: "753", name: "Novo Banco Continental S.A. - BM" },
  { code: "754", name: "Banco Sistema" },
  { code: "755", name: "Bofa Merrill Lynch BM S.A." },
  { code: "756", name: "Sicoob" },
  { code: "757", name: "Banco Keb Hana do Brasil S.A." },
  { code: "759", name: "Bansur JM SCD S.A." },
  { code: "760", name: "Emcash Serv Financ Sep S.A." },
  { code: "761", name: "Urbano S.A. SCFI" },
  { code: "763", name: "Vue IP S.A." },
  { code: "764", name: "Independência CC" },
  { code: "765", name: "Pagsmile IP Ltda." },
  { code: "766", name: "LB Pay IP Ltda" },
  { code: "767", name: "Qore" },
  { code: "768", name: "Becker Financeira SA - CFI" },
  { code: "769", name: "99pay IP S.A." },
  { code: "771", name: "WX IP Ltda." },
  { code: "772", name: "CC Mecunp" },
  { code: "773", name: "Kiwify IP" },
  { code: "774", name: "Mova Sep S.A." },
  { code: "775", name: "Contaazul IP Ltda." },
  { code: "780", name: "Safetypay Brasil IP Ltda" },
  { code: "781", name: "Baru DTVM Ltda." },
  { code: "783", name: "Swap IP S.A." },
  { code: "786", name: "Awx Brasil IP Ltda." },
  { code: "787", name: "Attrus IP S/A" },
  { code: "788", name: "Prototype IP S.A." },
  { code: "789", name: "Apusdigital IP Ltda." },
  { code: "790", name: "Max IP" },
  { code: "791", name: "Multiplike Financeira S.A. SCFI" },
  { code: "792", name: "Nixfin SCD" },
  { code: "793", name: "Magalupay SCFI S.A." },
  { code: "794", name: "Atual CC Ltda" },
  { code: "795", name: "Banco Traton Brasil S.A." },
]
